# Generated by Django 4.1.13 on 2024-06-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=39)),
                ('last_name', models.CharField(max_length=39)),
                ('email', models.EmailField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('date_birth', models.DateField()),
                ('status', models.CharField(choices=[('ACT', 'ACTIVE'), ('BAN', 'BANNED')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
